# Generated by Django 3.2.16 on 2023-03-18 06:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='publicated')),
                ('name', models.CharField(max_length=30, verbose_name='title of cotegory')),
                ('image', models.ImageField(null=True, upload_to=main.models.upload_to, verbose_name='image of category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='publicated')),
                ('name', models.CharField(max_length=30, verbose_name='name of product')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='price')),
                ('disccount_percent', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='ostatok')),
                ('Category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=main.models.upload_to, verbose_name='image of product')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='main.product', verbose_name='tovar')),
            ],
        ),
    ]
