# Generated by Django 3.2.16 on 2023-03-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_product_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='slag',
            field=models.SlugField(default='', verbose_name='CHPU'),
        ),
    ]
